# Generated by Django 2.2.4 on 2020-06-11 14:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=200, primary_key=True, serialize=False)),
                ('status', models.IntegerField(default=0)),
                ('image', models.ImageField(default='', upload_to='images/cottages/')),
            ],
        ),
    ]
